batch_size: 64
cuda: true
dataset: uestc
debug: false
expname: exps
folder: recognition_training
glob: true
glob_rot:
- 3.141592653589793
- 0
- 0
lr: 0.0001
max_len: -1
min_len: -1
modelname: recognition
num_epochs: 100
num_frames: 60
num_seq_max: -1
pose_rep: rot6d
sampling: conseq
sampling_step: 1
snapshot: 50
translation: false
